- name: policy timeout rule
  hosts: localhost
  tasks:
    - name: Timeout Policy - Test
      willguibr.zpacloud.zpa_policy_timeout_rule:
        name: "Timeout Policy - Test"
        description: "Timeout Policy - Test"
        action: "RE_AUTH"
        rule_order: 1
        reauth_idle_timeout: 600
        reauth_timeout: 172800
        state: absent
      register: created_rule
    - debug:
        msg: "{{ created_rule }}"
