name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ansible_collections/willguibr/zpacloud

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./ansible_collections/willguibr/zpacloud

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.8.10

      - name: Install pipenv
        run: |
          pip install pipenv

      # - name: Check pipenv cache
      #   id: cache-pipenv
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pipenv-

      - name: Install dependencies
        # if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Fix format
        run: |
          pipenv run make format

      - name: Check format
        run: |
          pipenv run make check-format

      - name: ansible-test sanity
        run: |
          pipenv run ansible-test sanity --python 3.8

      - name: ansible-galaxy collection build
        run: |
          pipenv run make build

  release:
    name: release
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Galaxy auth
        run: |
          mkdir -p ~/.ansible
          echo "token: $GALAXY_API_KEY" > ~/.ansible/galaxy_token
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
        shell: bash

      - name: Adjust Permissions
        run: |
          chmod +x .github/set-version.sh
          chmod +x .github/do-release.sh

      - name: Create release and publish
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            conventional-changelog-conventionalcommits@^4.4.0
            @semantic-release/git@^9.0.0
            @semantic-release/exec@^5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store built collection
        uses: actions/upload-artifact@v2
        with:
          name: collection
          path: |
            *.tar.gz

  docs:
    name: docs
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ansible_collections/willguibr/zpacloud

    steps:
      # Just a note here:  The Ansible stuff is apparently doing realpath
      # checks, so trying to simlink stuff and then run Ansible commends
      # such as ansible-test in the symlink directory fails.  Thus we need
      # to have the real path contain ansible_collections/willguibr/zpacloud.
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./ansible_collections/willguibr/zpacloud

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.8.10

      - name: Install pipenv
        run: |
          pip install pipenv

      # - name: Check pipenv cache
      #   id: cache-pipenv
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pipenv-

      - name: Install dependencies
        # if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Build the collection
        run:
          ansible-galaxy collection build

      # - name: Download built collection
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: collection

      - name: Install built collection
        run:
          ansible-galaxy collection install *.tar.gz

      - name: Generate documentation
        run: |
          pipenv run make docs

      # This is here for right now because the action to deploy seems to assume
      # (and not have a configuration option to) mirror the actions/checkout@v2
      # the with.path spec.
      - name: Move the repo to where the deploy action is looking for it
        run: |
          cd ../../../..
          mv zpacloud-ansible the_repo
          mv the_repo/ansible_collections/willguibr/zpacloud zpacloud-ansible
          mkdir -p zpacloud-ansible/ansible_collections/willguibr/zpacloud

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          clean: true
